### ISSUE TITLE
[[a,b],[c,d]] is not rendered

### ISSUE THREAD

**Issue by sebi5361** [tylingsoft/markdown-plus#111]
````
```AsciiMath
[[a,b],[c,d]]
```
````
is not rendered properly.
Instead getting:
![image](https://user-images.githubusercontent.com/18078043/95696804-e84f1500-0c3c-11eb-9dad-c038663626e2.png)

**Comment by tylerlong** [comment]
AsciiMath has been removed. Now it only supports Katex.
