### ISSUE TITLE
[Mac app] footnotes support

### ISSUE THREAD

**Issue by tylerlong** [tylingsoft/markdown-plus#13]
Some one is requesting this feature.

Footnote is not part of markdown specification, It's part of MultiMarkdown specification:

https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#footnotes

**Comment by tylerlong** [comment]
It seems that marked doesn't support footnotes yet.

Have to either switch for another markdown parser or hack marked to add footnote feature.

**Comment by sbugzu** [comment]
Need 2

**Comment by tylerlong** [comment]
Latest version supported:

Web: http://mdp.tylingsoft.com/
Mac: https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
Windows: https://gumroad.com/l/mdp-win

![screen shot 2015-12-29 at 11 56 49 pm](https://cloud.githubusercontent.com/assets/733544/12037223/e29ff966-ae87-11e5-8c72-ee89acaef431.png)

![screen shot 2015-12-29 at 11 57 29 pm](https://cloud.githubusercontent.com/assets/733544/12037233/f8c651fe-ae87-11e5-8344-0b9e4797ea2a.png)
