### ISSUE TITLE
Complete Symbol Support

### ISSUE THREAD

**Issue by saxisuer** [tylingsoft/markdown-plus#22]
1. Complete Symbol maybe more useful in code typing
2. Can I change theme in Version 1.3.4 or next version

**Comment by tylerlong** [comment]
change editor theme support was added in version 1.3.6, you'd have to wait for the new Mac app.

Auto complete brackets is useful feature, will support it in future versions

**Comment by tylerlong** [comment]
About auto complete symbols, I found this api:  http://ace.c9.io/api/editor.html#Editor.setBehavioursEnabled

But it doesn't work for markdown yet: https://github.com/ajaxorg/ace/issues/1393

**Comment by tylerlong** [comment]
Close it for now. Because this behavior depends on the ACE editor which I have no direct control.
