### ISSUE TITLE
[Mac app] 多窗口支持

### ISSUE THREAD

**Issue by qdaxb** [tylingsoft/markdown-plus#27]
很多场景需要打开多个文档同时查看，现在好像只能打开一个窗口？

**Comment by tylerlong** [comment]
是的，有这个问题。 感谢反馈，后续版本会解决。

之前创建了一个类似的issue https://github.com/tylingsoft/markdown-plus/issues/21

我想的是要么实现多窗口，要么实现多tab。有些编辑器两个都实现了，比如textmate。

**Comment by tylerlong** [comment]
支持多Tab了，如同浏览器一样，更加方便。

Latest version supports **Multiple Tabs**:

Mac: https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
Windows: https://gumroad.com/l/mdp-win

![screen shot 2015-12-29 at 11 20 04 pm](https://cloud.githubusercontent.com/assets/733544/12037268/448e9f38-ae88-11e5-9c69-70a047dd3cd4.png)

![image](https://cloud.githubusercontent.com/assets/733544/12037272/4f8e48fc-ae88-11e5-8272-d2c05f953813.png)
