### ISSUE TITLE
Flowchart diagram is truncated from below

### ISSUE THREAD

**Issue by Hunter-Github** [tylingsoft/markdown-plus#3]
``````
 ```
 graph LR
 A-->B
 B-->C
 C-->A
 D-->C
 ```
``````

results in 
![snapshot1](https://cloud.githubusercontent.com/assets/9477484/6682616/58c0e486-cc8c-11e4-9834-447458b328df.png)

Environment:
Node 0.12.0
Firefox 36.0.1

**Comment by tylerlong** [comment]
Confirmed. Flowchart feature is based on https://github.com/knsv/mermaid. I have created an issue to let them know: https://github.com/knsv/mermaid/issues/140.

**Comment by tylerlong** [comment]
It is fixed:

![screen shot 2015-12-29 at 11 53 35 pm](https://cloud.githubusercontent.com/assets/733544/12037189/7d97dfe8-ae87-11e5-8630-f40fe2c216a0.png)

**Comment by Hunter-Github** [comment]
Great, thanks!
