### ISSUE TITLE
[Mac OS] Issue with service context menu

### ISSUE THREAD

**Issue by tylerlong** [tylingsoft/markdown-plus#30]
![screen shot 2015-04-12 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/733544/7104756/7bd546f4-e129-11e4-87c4-31e6367e3027.png)

![screen shot 2015-04-12 at 3 35 06 pm](https://cloud.githubusercontent.com/assets/733544/7104762/8fb9bede-e129-11e4-89f2-2e425e4d193b.png)

An user reported the issue above. It might has something to do with Ace, the user said that other apps using Ace also have issues with service context menu.

**Comment by tylerlong** [comment]
I did a test here: http://ace.c9.io/build/kitchen-sink.html

select some text, right click, services > Search with Google, no matter what I select, a question mark is searched instead.

So I think this is an Ace issue. https://github.com/ajaxorg/ace/issues/2446

**Comment by lastobelus** [comment]
I opened a more specific issue: ajaxorg/ace#2662.

Also affects [HappenApps Quiver](http://happenapps.com/#quiver), which I use heavily these days: HappenApps/Quiver#163

**Comment by tylerlong** [comment]
Close it for now because it depends on ACE editor which I have no direct control. I always keep the dependent libraries up-to-date so as long as this issue is fixed in ACE it will also be fixed in Markdown Plus.

And by the way there is a workaround: Don't do the selection inside editor, do it in the preview.
