### ISSUE TITLE
suggesion: add a "print" button in the online version

### ISSUE THREAD

**Issue by fyears** [tylingsoft/markdown-plus#31]
Due to the limitation of web pages, it may not easy to export pdf in the front end.

However, here is a work around, use Chrome to open http://mdp.tylingsoft.com/, then open the "Inspect Element" tool, input `window.print();` in the console, then we may be able to print the page to pdf with the help of browsers.

My suggestion: add a "print" button in the toolbar in the online version that triggers the `window.print();` function, which helps users export the pdf.

:-) Thanks for the good product!

**Comment by tylerlong** [comment]
Please try keyboard shortcut `Cmd-P` (or `Ctrl-P` if you use Windows).

And you can also trigger print via menu: File > Print...

So adding a new button might be convenient but not necessary.
