### ISSUE TITLE
Key Binding 选 Vim 时，中文输入法的光标停在原地不动

### ISSUE THREAD

**Issue by solicomo** [tylingsoft/markdown-plus#32]
光标不随着输入往后移动。

![Key Binding Vim](https://i.imgur.com/NpRQrWS.png)

**Comment by tylerlong** [comment]
我测试了下，确实有这样的问题。
不过一旦选中了中文之后，光标还是会跳到最后的。 就是在选词预览阶段，光标不动。结束选词，一切恢复正常。基本不影响使用吧。

**Comment by tylerlong** [comment]
此问题不影响使用，暂时忽略。如有问题，请 Re-Open
