### ISSUE TITLE
[Mac app] open file from command line

### ISSUE THREAD

**Issue by tylerlong** [tylingsoft/markdown-plus#34]
Such as:

```
mdp test.md
```

**Comment by ghost** [comment]
:+1:  on this request  also Tabs more that one file open at a  time?

**Comment by tylerlong** [comment]
I am busy with version 2.0 which supports multiple tabs. It will be released this month.

**Comment by tylerlong** [comment]
Multiple tabs feature has been implemented.

In order to launch the app from command line, you can add the following line to `~/.bash_profile`:

```
alias mdp="open -a /Applications/Markdown\ Plus.app"
```

Then you can:

```
mdp README.md
```

or just 

```
mdp
```
