### ISSUE TITLE
Best markdown editor

### ISSUE THREAD

**Issue by hai046** [tylingsoft/markdown-plus#36]
这是我见过最好最强大的markdown，首先感谢一下你们

另外如果能全屏预览就更好了  非常感谢！

**Comment by tylerlong** [comment]
感谢夸奖！

新版已发布，前后端全部重写：

https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
https://gumroad.com/l/mdp-win

功能上和旧版相比不可同日而语。

请试用后再给反馈。 感谢支持！
