### ISSUE TITLE
建议1增加编辑快捷键 2插入表格的问题 其他

### ISSUE THREAD

**Issue by greylink** [tylingsoft/markdown-plus#38]
1. 建议支持编辑快捷键       如   Ctrl +B   =  加粗
2. 目前插入的表格为 

| header 1 | header 2 |
| --- | --- |
| row 1 col 1 | row 1 col 2 |
| row 2 col 1 | row 2 col 2 |

但是在github  或者其他网站  他们只认  下面这种格式   （既两端都有  | ），希望兼容

| Tables        | Are           | Cool  |
|这一行我忽略掉了
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1|
1. 其他优化
            - 导出pdf 或者image时  Save窗口预设文件名（如：当前编辑的文件叫做 demo.rd 预设的保存文件名则为 demo.pdf）
            - 支持窗口拖入文件用于 open file
2.  settings 界面在全屏情况下  无法操作 （Windows 7 64位  双屏）

**Comment by tylerlong** [comment]
settings全屏界面下有问题，这个已经确认过了。 底层的CefSharp的bug，等待那边修复。

关于表格的语法，https://help.github.com/articles/github-flavored-markdown/  目前应该是合乎规定的。 其它地方无法显示，那是他们的问题。

快捷键和其它优化，感谢建议，会考虑添加的。

**Comment by tylerlong** [comment]
> 其他优化
> - 导出pdf 或者image时 Save窗口预设文件名（如：当前编辑的文件叫做 demo.rd 预设的保存文件名则为 demo.pdf）
> - 支持窗口拖入文件用于 open file
> 
> settings 界面在全屏情况下 无法操作 （Windows 7 64位 双屏）

以上问题最新版已经全部解决掉了。

关于表格语法，合乎规范。另外GitHub也是支持那种写法的。 其它网站具体是指？原则上讲那是它们的兼容性问题，倾向于不去迁就它们。

请升级到最新版再测：

https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
https://gumroad.com/l/mdp-win

---

> 建议支持编辑快捷键 如 Ctrl +B = 加粗

这个事情我给忘了。等解决了再关闭这个 issue

**Comment by tylerlong** [comment]
1.8.9 版新增快捷键：

<kbd>Ctrl</kbd> + <kbd>B</kbd> = 粗体
<kbd>Ctrl</kbd> + <kbd>I</kbd> = 斜体
<kbd>Ctrl</kbd> + <kbd>U</kbd> = 下划线
