### ISSUE TITLE
建议1增加编辑快捷键 2插入表格的问题 其他

### ISSUE THREAD

**Issue by greylink** [tylingsoft/markdown-plus#39]
建议支持编辑快捷键       如   Ctrl +B   =  加粗

编辑器自动插入的表格 在gitosc  和 coding 上都没发正常显示  都变成文字了
Key |Type |Vlaue |Explain ---|--- ID |String |OTA | ACTION |String |ReqInstallPkg |

其他建议

导出pdf 或者image时  Save窗口预设文件名（如：当前编辑的文件叫做 demo.rd 预设的保存文件名则为 demo.pdf）

支持窗口拖入文件用于 open file

增加文件关联（目前右键  然后 用MPlus.exe  打开文件后，mplus是一片白  不能用

settings 界面在全屏情况下  无法操作 （Windows 7 64位  双屏）

**Comment by tylerlong** [comment]
duplicate
