### ISSUE TITLE
内容多时有明显卡顿

### ISSUE THREAD

**Issue by freemantbs** [tylingsoft/markdown-plus#40]
如题，已在app和在线模式都进行了测试，测试内容有1400+行，进行编辑时有明显的1-2秒卡顿

环境：
Markdown Plus（Version 1.4.4）
OSX Yosemite 10.10.4
MacBook Pro (Retina, 13-inch, Late 2013)
2.4 GHz Intel Core i5
8 GB 1600 MHz DDR3

**Comment by tylerlong** [comment]
是否有图片 404 无法访问？ 已知这种情况下卡顿会很严重。

另外可否提供内容原文，可以发送到邮箱 service@tylingsoft.com  敏感内容可以替换掉。

**Comment by freemantbs** [comment]
发给你了

**Comment by tylerlong** [comment]
新版已经发布，请再测。前后端全部重写，包括markdown的解析引擎都换掉了。

建议升级：

https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
https://gumroad.com/l/mdp-win

如仍有问题请再另开 issue。

另外，代码逻辑中指定：用户停止输入256毫秒才更新预览。如果用户打字很快，一直不停，就一直不更新预览，看起来是“卡顿”，其实是有意为之。 不知是否这个问题。 不管怎样，请测新版，有问题再开issue。
