### ISSUE TITLE
Bought your app today on App Store

### ISSUE THREAD

**Issue by jocubeit** [tylingsoft/markdown-plus#42]
Would love the ability to show/hide the toolbar... I find it quite distracting since I know markdown and don't use the toolbar buttons for formatting etc. Any chance we can get an update with the ability to turn it off?

**Comment by tylerlong** [comment]
Click the separator line between the toolbar and the main content to toggle the toolbar. Let me know if it works for you.

**Comment by jocubeit** [comment]
Hey look at that - it works! I'm very happy. Did I miss that somewhere in the instructions? Now all I need is for math formulae, flow charts, sequence diagrams and Gantt charts to be able to render in my Gitlab and Github READMEs!

I love MDP and have submitted a glowing review for you in the App store (see Kodemunki).

**Comment by tylerlong** [comment]
Unfortunately GitHub Flavored Markdown doesn't support "math formulae, flow charts, sequence diagrams and Gantt charts". So GitHub READMEs cannot render them.

An alternative way is to export your markdown file as HTML and publish the HTML to GitHub Pages.

**Comment by jocubeit** [comment]
Excellent idea - thanks.
