### ISSUE TITLE
希望支持自动生成目录树

### ISSUE THREAD

**Issue by greylink** [tylingsoft/markdown-plus#44]
希望能够有快捷方式自动按照h标签生成目录树,另外打听一下下一版本预计什么更新.
谢谢

**Comment by tylerlong** [comment]
最近一段时间，因为忙其它项目，这个开发暂缓了，非常抱歉。很快就会回归。不敢做很明确的承诺，年底之前肯定会有更新。

目录树在呈现方式上面纠结了很久。 比如是直接插入 <ul> ? 还是用级联下拉？ 还是左侧导航？

**Comment by saxisuer** [comment]
可以参考CMD MARKDOWN 或者马克飞象里面的目录树功能啊 
用户输入TOC 以后 触发效果

**Comment by tylerlong** [comment]
1.8.9 版已支持。
