### ISSUE TITLE
建议图片标签支持本地文件路径

### ISSUE THREAD

**Issue by greylink** [tylingsoft/markdown-plus#45]
如.表示当前目录

 #2.系统框图
![Alt text](./666.png)

![Alt text]--./666.png)

**Comment by tylerlong** [comment]
你是指网站还是app？

网站是没有办法访问你的硬盘的。 app的话目前支持绝对路径，相对路径不支持。

**Comment by tylerlong** [comment]
最近更新：
1. Windows版最新版，支持本地图片，相对路径和绝对路径都可以
2. Mac 版最新版，支持本地图片，但仅支持绝对路径， 下次升级会支持相对路径！

建议升级：

https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
https://gumroad.com/l/mdp-win

这个 issue 等 Mac 版也支持本地图片相对路径了再关闭。

**Comment by tylerlong** [comment]
1.8.9 版本已支持。 包括Windows版和Mac 版，相对路径和绝对路径，全部都支持。
