### ISSUE TITLE
Math formulas

### ISSUE THREAD

**Issue by petrleocompel** [tylingsoft/markdown-plus#46]
Math formulas are little bit crazy.

I follow https://meta.wikimedia.org/wiki/Help:Displaying_a_formula

&sigma; => \sigma
and so long..
But how to write & symbol
syntax \And throw error
Also \mathbb{letter} does not work

**Comment by petrleocompel** [comment]
Maybe solved -> updated KaTeX component of app :blush:

**Comment by petrleocompel** [comment]
Stil not work in app :-1:

**Comment by tylerlong** [comment]
Currently working on Markdown Plus version 2.0 which will be released in next month.

There will be no update to version 1.x.

Sorry for the inconvenience!

**Comment by petrleocompel** [comment]
Will be v2 free for owners v1 ? i hope so because i bought it just before few weeks.

**Comment by tylerlong** [comment]
@petrleocompel of course free for v1 users!

**Comment by petrleocompel** [comment]
OK :+1:
