### ISSUE TITLE
含有iframe的文档会自动打开浏览器

### ISSUE THREAD

**Issue by tufu9441** [tylingsoft/markdown-plus#47]
在md文档中插入iframe代码后，每次用markdown plus打开文件时会自动启动浏览器并显示iframe中的内容，切换回markdown plus继续编辑后，也会不断地跳到浏览器窗口，无法继续正常写作。

**Comment by tylerlong** [comment]
收到。 任何新的url请求都通过外部浏览器打开。比如你点击预览中的链接。 如果在当前app打开，那么预览就不见了。

iframe的问题真没有考虑到。因为iframe其实也是一个新的url请求。我尽快研究下怎么解决。

**Comment by tylerlong** [comment]
新版本已经解决这个问题，包括 Windows 版和 Mac 版，建议升级：

https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
https://gumroad.com/l/mdp-win
