### ISSUE TITLE
能否给个设置，打开软件默认显示空白页，当前是显示上一次编辑的文档..

### ISSUE THREAD

**Issue by lwbjing** [tylingsoft/markdown-plus#48]
RT

**Comment by tylerlong** [comment]
新版本发布了。 支持多tab页。 如果你关闭软件的时候，关闭了所有的tab页，那么下一次打开就会显示空白窗口。否则，就会自动打开上一次的tab。

旧版本确实很别扭，只有唯一的一个编辑窗口，还无法关闭（除非关闭整个软件）。旧版本不再更新，也不再提供支持，建议尽快升级：

https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12
https://gumroad.com/l/mdp-win
