### ISSUE TITLE
Emacs key binding 支持太差

### ISSUE THREAD

**Issue by ghost** [tylingsoft/markdown-plus#49]
弱不堪用。
ctrl+n = new file 而不是next line
ctrl+shift+-根本不能撤销
不能打开上次编辑的文档，每次都要重新打开
程序经常假死
值60块？

**Comment by tylerlong** [comment]
Emacs 支持是从 ACE editor 那里继承来的。

ctrl + n 这个属于冲突了，要么就牺牲emacs，要么就删除new file这个快捷键， 没有更好的办法。

ctrl+shift+-根本不能撤销  这个你可以向ACE Editor 提bug

你用的是ctrl组合键，可见是windows版。Windows版免费下载试用的。满意的人才会付款。

月内2.0版将要发布了，几乎是重写了主体代码。敬请期待吧！
