### ISSUE TITLE
左右区域的滚动在有多张图片时严重错位

### ISSUE THREAD

**Issue by AlloVince** [tylingsoft/markdown-plus#5]
当Markdown中插入很多图片后，Prevew区域的滚动应该按内容同步而不是百分比

**Comment by tylerlong** [comment]
确实会有这样的问题。 未来版本会想办法改进。

**Comment by tylerlong** [comment]
已更新。 最新版本按heading同步。 
即 h1 － h6 的标题 以可视区域最上方为参照，右侧与左侧是同步的。
当左侧编辑器显示第一行为一个heading时，右侧预览最上方也显示这个heading。
相邻两个heading之间的内容是按照百分比同步的。

**Comment by tylerlong** [comment]
如果相邻两个heading之间的内容很长， 同步还是会有瑕疵。
我看了下stackedit等编辑器，它们也没有很好地解决这个问题。
更加好的办法是把`<p>`的相对同步也考虑进来。 下个版本可能会在这方面进一步加强。

**Comment by AlloVince** [comment]
赞！目前确实没有特别好的方法，能按heading同步已经能满足大部分需要了

**Comment by tylerlong** [comment]
v1.3.8 版本进一步改进了这个问题。 现在所有的顶级元素都是左右同步的， 包括 heading, `<p>`, `<table>`,`<ul>`,`<pre>`,`<blockquote>` 等等。
左右滚动同步应该已经做到极致了。

**Comment by AlloVince** [comment]
试了一下效果，非常赞
