### ISSUE TITLE
首先赞一下这个软件

### ISSUE THREAD

**Issue by HardySimpson** [tylingsoft/markdown-plus#50]
然后windows下有个问题，把md设置为用mps打开的时候，出来是一个卡死的untitiled的窗口。

**Comment by tylerlong** [comment]
正在开发2.0版。前端代码已经全部重写了，等待整合到github项目中。

Mac版月内上线，Win版要再晚半个月。

Win之前的版本是用WPF写的，接下里准备用UWP写。 相当前端后端全部重写。所以现在的问题将来不一定会有。 故而先放在这里。 敬请期待2.0版本！

**Comment by HardySimpson** [comment]
ok，发行了我就买一份，哈哈

**Comment by HardySimpson** [comment]
2.0版开发的怎么样啊？目前的几个markdown编辑器我都找不到好用的。。。就等你的了。

**Comment by tylerlong** [comment]
昨天已经提交Mac App Store审核了，预计一个星期后可以更新（如果运气不好，审核不过，要再多等一个星期）。这次暂时只有Mac版更新。

![screen shot 2015-11-30 at 10 15 51 am](https://cloud.githubusercontent.com/assets/733544/11462192/e33c698e-974b-11e5-9ffb-ca7383e9a2ed.png)

**Comment by HardySimpson** [comment]
赞，等windows版更新。

**Comment by tylerlong** [comment]
两个版本全部更新了，你提到的问题已经不存在了。

Mac 版：https://itunes.apple.com/us/app/markdown-plus/id972585766?ls=1&mt=12

![screen shot 2015-12-29 at 11 20 04 pm](https://cloud.githubusercontent.com/assets/733544/12036775/186a2250-ae84-11e5-81b0-03dc6c65a651.png)

Windows 版： https://gumroad.com/l/mdp-win

![image](https://cloud.githubusercontent.com/assets/733544/12036779/20113fde-ae84-11e5-9c41-d6f87464075b.png)

**Comment by HardySimpson** [comment]
求支付宝或微信的支付链接~~

**Comment by tylerlong** [comment]
新官网还在建设中。 你可以直接支付宝付款到 15889546648  刘春涛  (对应两个账号，哪个都可以)。目前中国用户特惠价格 60 人民币 （https://gumroad.com/l/mdp-win 售价为 14.99 美刀）。

付完款后发邮件到 service@tylingsoft.com 注明支付宝交易号。 确认后一个工作日内发下载链接和注册码。

感谢支持！
