### ISSUE TITLE
markdown-plus.js 和 dist/markdown-plus.min.js有什么区别?

### ISSUE THREAD

**Issue by y9c** [tylingsoft/markdown-plus#51]
markdown-plus.js 和 dist/markdown-plus.min.js有什么区别?
依赖关系是怎样的?

**Comment by tylerlong** [comment]
请参考 https://github.com/tylingsoft/markdown-plus/blob/master/fabfile.py 文件， 其中的 `def js():` 脚本负责生成 dist/markdown-plus.min.js

简单讲：dist/markdown-plus.min.js 包含了 markdown-plus.js  以及很多第三方的库。

**Comment by y9c** [comment]
那是不是clone 到本地后不需要markdown-plus.js这个文件也能运行?

**Comment by y9c** [comment]
文件依赖写得太复杂了
看了很久还是没理清楚.
我删除了很多文件,只剩下index.html和dist文件夹. 也能完全执行

**Comment by tylerlong** [comment]
必须的就只有dist。 dist 顾名思义： distribution。index.html 是用户根据自己的需求写的，没必要用项目自带的，所以也不是必须的

**Comment by y9c** [comment]
那么dist/fonts和dist/css/fonts有特殊用意么? 为什么要区分开呢?

**Comment by tylerlong** [comment]
第三方库要求文件夹结构这么放。

**Comment by y9c** [comment]
谢谢你
