### ISSUE TITLE
一定要放置<boby>的直接子结点上吗？

### ISSUE THREAD

**Issue by xaero7** [tylingsoft/markdown-plus#52]
一定要放在`<boby>`的直接子结点上吗？
貌似放到子节点的子节点上就报错？？

```
UI Layout Initialization Error
The center-pane element does not exist.
The center-pane is a required element
```

能嵌入到某个div内吗，然后自己搞全屏或非全屏吗？

**Comment by tylerlong** [comment]
layout 是借助 这个项目实现的： http://layout.jquery-dev.com/index.cfm

根据这里，你的需求是可以实现的：http://stackoverflow.com/questions/20557091/jquery-ui-layout-on-a-container-div-instead-of-body

这里是一个非全屏非body节点layout的例子： http://jsfiddle.net/JPEaa/223/

这个项目最起初是为App服务的，很多地方写得比较死。接下来会改进一下，提供一些容易使用的api。将来可以通过这样的方式一行代码搞定：

``` javascript
mdp.create('id-of-div');
```

等上述API可用了再关闭这个issue。

**Comment by xaero7** [comment]
貌似没用啊，还是和上面一样的提示。
我在外面套了一层：

``` html
<div id="mydiv">
   ...//index.html样例中<div class="ui-layout-north">开始的代码
</div>
```

然后是js：

``` html
<style>
    #mydiv {
    position:relative;
    width:700px;
    height:700px;
}
</style>
<script type="text/javascript">  
$(document).ready(function () {  
    $('#mydiv').layout({ applyDefaultStyles: true });  
});  
</script> 
```

**Comment by tylerlong** [comment]
要改这里的源码： https://github.com/tylingsoft/markdown-plus/blob/master/markdown-plus.js#L104

我建议你等等看。 我接下来会改进API的通用性。 目前的版本确实没有考虑到在其它各种环境中使用的情况。

**Comment by xaero7** [comment]
感谢！:+1:

另外问问，从数据库读取出md文本后，在html页面上怎么显示？

**Comment by tylerlong** [comment]
https://github.com/tylingsoft/markdown-plus/blob/master/index.js#L3

**Comment by xaero7** [comment]
我的意思是如何将md文本渲染成html代码

**Comment by tylerlong** [comment]
两种方法：

一种是先设置左侧编辑器的值，再读取右侧的html：

``` javascript
editor.session.setValue(markdown, -1);
setTimeout(function(){ console.log($('article#preview').html()); }, 1000); // 等待1000毫秒，页面渲染完毕
```

还有一种是直接调用api：

``` javascript
var html = mdc.render(markdown);
```

第二种方式又快又简单，可以纯server端搞定。但是不支持mermaid图表，因为mermaid必须得借助客户端浏览器。

**Comment by xaero7** [comment]
纯server端搞定是用nodejs吗？
php这种能处理么？

**Comment by tylerlong** [comment]
node.js. 
php的话还得借助客户端浏览器执行那条语句.

**Comment by xaero7** [comment]
ok，谢谢

**Comment by ogoodo** [comment]
mdp.create('id-of-div'); 
希望这种方式的api快点出来
不然考虑在iframe里使用了

**Comment by xaero7** [comment]
这样的api啥时候能出来？
`mdp.create('id-of-div');`

**Comment by tylerlong** [comment]
不好意思，最近事情很多，虽然更新了很多内容，但是这个一直没有做。 有时间的请贡献代码。 我尽量抽空。

**Comment by tylerlong** [comment]
有进展了。 虽然不是当初预想的那种方式。

现在默认不是创建到`<body>`, 而是创建到`<div id="mdp-container">`。

`<div id="mdp-container">` 的位置可以随意放置， 大小可以通过css控制。

比如： `<div id="mdp-container" style="height: 300px;">`。
