### ISSUE TITLE
mermaid 不支持 chrome 48

### ISSUE THREAD

**Issue by FuDesign2008** [tylingsoft/markdown-plus#53]
mermaid 版本不支持 chrome 48,  see https://github.com/knsv/mermaid/issues/281

需要更新 mermaid 的版本

**Comment by tylerlong** [comment]
感谢汇报问题。 我测试了下，貌似flowchart确实有问题， 其它两种chart倒是还能运行。

我尽快升级。

**Comment by tylerlong** [comment]
已更新
