### ISSUE TITLE
请问如何部署markdown-plus开发环境？

### ISSUE THREAD

**Issue by xaero7** [tylingsoft/markdown-plus#55]
@tylingsoft
请问如何部署markdown-plus开发环境？就是能发不成js+css的，浏览器能用就行

**Comment by tylerlong** [comment]
不清楚你的问题具体是什么？ 想在浏览器中运行，最终都得落实到 js ＋ css 上面。

开发的时候，修改根目录的相关文件，然后运行 `fab dist`, 生成的文件在 `dist/` 目录 . 生成的文件可运行在浏览器中。我自己的开发流程就是这样的。 如果你只更新了 css，可以 `fab css`, 如果只更新了js，可以 `fab js`...etc.

使用 `fab` 这个命令你需要安装 http://www.fabfile.org/。 其它依赖的软件，没有安装的话出错信息会提示你。
