### ISSUE TITLE
请问css和js分别集成了那些项目？

### ISSUE THREAD

**Issue by xaero7** [tylingsoft/markdown-plus#59]
看了一下，css集成了Font Awesome
js有jquery，katex，highlight
其他有哪些？能介绍一下吗？

**Comment by tylerlong** [comment]
请参考以下两个文件：
1. https://github.com/tylingsoft/markdown-core/blob/master/fabfile.py
2. https://github.com/tylingsoft/markdown-plus/blob/master/fabfile.py

以上文件负责打包第三方类库的。
