### ISSUE TITLE
Create Visual Studio Code extension

### ISSUE THREAD

**Issue by chris5287** [tylingsoft/markdown-plus#60]
Have you thought about creating an extension for [Visual Studio Code](https://code.visualstudio.com/)?

Maybe something similar to https://marketplace.visualstudio.com/items?itemName=DougFinke.vscode-pandoc, but with all the Markdown Plus goodies :)

**Comment by tylerlong** [comment]
Whenever I have time, I will investigate.

**Comment by tylerlong** [comment]
Close it for now because it should be a separate project.
