### ISSUE TITLE
mdp-container一定要放在body下面吗？

### ISSUE THREAD

**Issue by jingyuan4ever** [tylingsoft/markdown-plus#61]
我在body下面放了一个div，里面放mdp-container，然后就渲染不出来了。

**Comment by tylerlong** [comment]
Read this: https://github.com/tylingsoft/markdown-plus/issues/58

**Comment by jingyuan4ever** [comment]
试了一下貌似height一定要用绝对值？

**Comment by tylerlong** [comment]
不必。 参考  https://github.com/tylingsoft/markdown-plus/blob/master/index.html#L13

如果不行也是CSS的问题，跟Markdown Plus本身无关。

**Comment by jingyuan4ever** [comment]
我就是按照这个文件写的，如果是css问题的话那么我该怎么处理呢？

**Comment by tylerlong** [comment]
http://stackoverflow.com/questions/1622027/percentage-height-html-5-css

**Comment by jingyuan4ever** [comment]
感谢，成功了。
