### ISSUE TITLE
问题: 保存和加载问题

### ISSUE THREAD

**Issue by linuxer-xyz** [tylingsoft/markdown-plus#63]
大哥, 请问一下,目前在markdown-plus里面有没有支持直接读文件的和保文件的功能?
#1 在js有没有提供,对话框直接读取文件,并在makrdown里面?
#2 有没有保存对话框架,可以将当前的文件保存至某一个文件中?

**Comment by tylerlong** [comment]
这个没有，也无法实现。 浏览器中的js代码是无法访问本地硬盘上的文件的。你能做的就只有上传和下载（而不是打开和保存）。需要服务器端支持，单靠js客户端实现不了。

Windows app 和 Mac app 都实现了文件的打开和保存，是通过原生代码实现的，不是通过js。
