### ISSUE TITLE
插入LaTeX公式的时候，不能带汉字

### ISSUE THREAD

**Issue by gujunhk** [tylingsoft/markdown-plus#64]
> code:
> 
> ``` latex
> `$\color{red}{ABC好}$`
> ```
> 
> result:
> 
> ```
> ParseError: KaTeX parse error: Unexpected character: '好' at position 15: \color{red}{ABC̲好}
> ```

**Comment by tylerlong** [comment]
Please report this issue to https://github.com/Khan/KaTeX.  LaTex feature is based on KaTex.
