### ISSUE TITLE
How can it don't translate string like ":s" to emoji?

### ISSUE THREAD

**Issue by HolyChen** [tylingsoft/markdown-plus#65]
I need input "std::string", and get output like "std::string". But it translates the string to an emoji. How can I get "std::string" rather than an "std:[emoji]tring". Thanks.

**Comment by tylerlong** [comment]
I think it is a bug. I will try to fix it.

As a temporary workaround, you can write it as inline code: 

```
`std::string`
```

It will be rendered as `std::string`.

**Comment by tylerlong** [comment]
Fixed in version 2.0.0
