### ISSUE TITLE
YouDao Note used this project without any copyright or permission notice.

### ISSUE THREAD

**Issue by HolyChen** [tylingsoft/markdown-plus#66]
YouDao Note(http://note.youdao.com/index.html) is the largest online note application in China.

In Mar. 9th 2016, it updated markdown note edit function. Excluding it disable the HTML target and "[toc]", the function of it is **SAME** as the project markdown-plus, even in "Emoji", "Fontawesome" and HTML style!  But I can't find any information about project markdown-plus, i.e. there is no copyright notice or this permission notice in the soft or website. I think it violated the  MIT licence.

If you need any help, welcome to contact with judicial department or media in PRC.

**Comment by tylerlong** [comment]
Thank you for reporting this. 😄 

It is OK since Markdown Plus is MIT licensed.
