### ISSUE TITLE
我如何在ghost里面集成markdown-plus

### ISSUE THREAD

**Issue by phpmaple** [tylingsoft/markdown-plus#68]
这样我就可以markdown-plus 写好直接复制markdown粘贴到ghost发布，ghost不能直接发布html

**Comment by tylerlong** [comment]
我没有ghost的经验，也不是ghost的开发者。有以下几个问题：
1. ghost 支持 markdown 吗？
2. ghost 支持 markdow-plus 的扩展语法吗？ 比如说math， diagram， footnote等等。

如果不支持，你可以向ghost项目提issue。如果你觉得 markdown-plus 这边可以帮你做什么，请回复。

**Comment by tylerlong** [comment]
markdown-plus 的 app 可以导出 html。 我想 ghost 至少应该是支持 html 的。 你可以直接发布html到ghost。

**Comment by phpmaple** [comment]
ghost发布默认都是markdown格式，但是markdown里面可以直接放入html，但是当同时存在sequenceDiagram和gantt的时候图片就显示不出来了，如果只有一个是可以的，不知道是什么问题

**Comment by tylerlong** [comment]
导出的diagram可以是png格式，也可以是svg格式。你要不都尝试下？ 具体参考这里： https://github.com/tylingsoft/markdown-plus-plugins#svg-charts-in-exported-html

通过装一个插件，导出的diagram为svg格式。也许ghost对svg的兼容性更好些。

**Comment by phpmaple** [comment]
这个公式可以显示，其他都不可以了，好吧- - !

**Comment by tylerlong** [comment]
这个我也没有办法了。建议你向 ghost 提 issue： 为什么内嵌在 markdown 的 html 无法正常显示？

另外你直接粘贴markdown过去它不能支持很正常。 因为math，diagram这些本身就不是markdown的规范里面的东西。markdown-plus 支持了markdown的扩展语法。 如果想到处能兼容，要么就别用这些语法，要么就直接贴图片（截图，然后贴过去）。

另外你上面说的png和svg图片都无法显示，这个无法理解。

**Comment by tylerlong** [comment]
Close it for now. Feel free to create new issues.
