### ISSUE TITLE
配合其他插件使用时有冲突

### ISSUE THREAD

**Issue by crazylovecat** [tylingsoft/markdown-plus#69]
页面上同时使用了dialog.js：http://www.htmleaf.com/jQuery/Lightbox-Dialog/201606083573.html

dialog.js使用的是confirm类型，但是click之后提示：Uncaught TypeError: $.dialog is not a function

调试时能看到$符号使用的并不是dialog.js内部的，而是markdown-plus.min.js内的对象。

是否有办法避免这种冲突？

**Comment by tylerlong** [comment]
markdown-plus.min.js 内置了 jquery。 你不需要再安装jquery。 

看你的消息提示，好像是插件安装没成功。按我上面说的试下看看。

**Comment by crazylovecat** [comment]
@tylerlong ok，已经fix了
