### ISSUE TITLE
请问如果不想引入letex支持该如何删减

### ISSUE THREAD

**Issue by byteli** [tylingsoft/markdown-plus#70]
会触发警告:KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
不知fabric.py里可否配置不引入letex支持

**Comment by tylerlong** [comment]
没有相关配制项。 你需要自己定制。

markdown-plus 依赖  markdown-core.

markdown-core 这里可以把math相关的东西注释掉： https://github.com/tylingsoft/markdown-core/blob/master/markdown-core-node.js

改完发布一个你自己的markdown-core. 修改markdown-plus fabric.py 引用你自己的markdown-core.  `fab dist` 生成最终的markdown-plus文件。
