### ISSUE TITLE
not support code type of mermaid after ```, mermaid code is only rendered with ```  

### ISSUE THREAD

**Issue by supercoderhawk** [tylingsoft/markdown-plus#74]
When using code type of mermaid after  &#96; &#96; &#96; , like

```
` ` `mermaid
graph LR
    A(A) --> B(B)
    A(A) --> C(B)
` ` `
```

mermaid diagram will not be rendered.

only use that:

```
` ` `
graph LR
    A(A) --> B(B)
    A(A) --> C(B)
` ` `
```

the mermaid diagram will be rendered.

**Comment by tylerlong** [comment]
Confirmed and will be fixed soon! Thank you!

**Comment by tylerlong** [comment]
fixed
