### ISSUE TITLE
[Win app] Open new file in the existing window

### ISSUE THREAD

**Issue by mikenils** [tylingsoft/markdown-plus#78]
A little issue about opening the files. When I'm double-clicking on a new file in windows file manager, the new window is opened, instead of just opening a new tab.

Here I double-clicked on the first file and on the second. The two windows are opened, instead of one.

![img1](https://cloud.githubusercontent.com/assets/23511057/20369073/215fddcc-ac68-11e6-97f3-d74a08962c7a.png)

![result](https://cloud.githubusercontent.com/assets/23511057/20369082/31ccb93c-ac68-11e6-91f6-84c89badce28.PNG)

![shoulbe](https://cloud.githubusercontent.com/assets/23511057/20369084/3506f43c-ac68-11e6-98f0-e3a2aa9b6907.PNG)

**Comment by tylerlong** [comment]
How about drag & drop the second file onto the window?  

To me the behavior is acceptable because there are other ways to open a file in existing window.
