### ISSUE TITLE
已经购入 支持作者，一定要勤更新啊~

### ISSUE THREAD

**Issue by saxisuer** [tylingsoft/markdown-plus#8]
- 发现sequence图的支持不是特别好。如果我的sequence很长...就没有办法展示完全。导出PDF的时候发现也是只有一部分。
-  求SQL语法高亮的效果能明显一点点~
- 是否可以支持生成目录 `[TOR]`  可以参考一下马克飞象的这个功能

**Comment by shajiquan** [comment]
生成目录是说生成 PDF 的目录（非内容部分的，是 pdf 的 table of contents）吗？还是预览时？

**Comment by tylerlong** [comment]
放心，绝对经常更新。 我自己也用它写东西，还计划写本电子书呢。会不断优化的。

App是上周送去Apple那边审核的，也就是上周的版本1.2.0. 现在的最新版 1.2.8 已经改进了语法高亮。可以在这里测试下最新版的高亮： http://mdp.tylingsoft.com/  很快就会再发一个版本，到时候记得更新。

关于顺序图，很长的图还真没测试过。 这个问题记下了。

生成目录特性一直在想，没有想到合理的方式。我有空看下马克飞象。

**Comment by saxisuer** [comment]
cmdMarkdown 和 马克飞象都有这个功能 看上去还是很不错的

**Comment by shajiquan** [comment]
我昨晚居然梦见作者已经解决了 pdf table of contents 的问题……囧。

**Comment by tylerlong** [comment]
亚历山大啊……好多人心的朋友向我反馈问题，提新的功能需求。 正在努力中……

**Comment by saxisuer** [comment]
#不
##要
###着
####急

坐等作者耐心迭代修复BUG

**Comment by saxisuer** [comment]
###不用着急啊，总体使用还是蛮开心的~ 后期作者感觉可以有很多扩展。
慢慢更新就好啦

**Comment by saxisuer** [comment]
不用着急啊~慢慢修复现有BUG ，后期新功能慢慢来。
感觉可以添加很多功能的

**Comment by tylerlong** [comment]
@saxisuer  最新版本的app增加了生成的PDF的页面宽度和长度（各增加50%）左右。 生成的sequence图被截断的情况不太容易发生了。

不过本周即将发布的（就这两天）app是上周提交的，不包含这个更新。 包含这个更新的app要多等一周左右。

![screen shot 2015-04-02 at 11 34 10 am](https://cloud.githubusercontent.com/assets/733544/6957342/3afd7458-d92c-11e4-80ee-e53a2a23e053.png)

**Comment by tylerlong** [comment]
Mac App 1.3.4 提前发布了。 你们反馈的问题，除了TOC，已经全部解决了。

TOC 我另外开一个issue。
