### ISSUE TITLE
中文支持问题

### ISSUE THREAD

**Issue by zipzou** [tylingsoft/markdown-plus#81]
不知道作者用的是什么环境，我放到tomcat容器中，使用EDGE打开，正常。如果是用chrome+tomcat的环境，输入中文会出现一系列的问题。
![f xdzvogecw5 s8ycxng 8](https://cloud.githubusercontent.com/assets/13446458/21748310/d77bc1e8-d5bc-11e6-9d1b-5f5afa3387fa.png)
![qj56kj sokby fti uc 9r](https://cloud.githubusercontent.com/assets/13446458/21748311/d7afe8b0-d5bc-11e6-9068-0e6f2dd6301d.png)
![8 2dzcius ur 05f 3 qw](https://cloud.githubusercontent.com/assets/13446458/21748312/d7e0b134-d5bc-11e6-9a0c-5316de2347d0.png)
如图所示，当输入中文时，当输入结束后，字符不会立马出现，当再打个空格时，空格会跑到中文的前面，中文较多时，更加有问题。把之前输入的中文内容删除后，输入新的内容，原来删除的内容也会奇怪的再次出现

**Comment by tylerlong** [comment]
是什么操作系统什么浏览器？

你在这里能重现吗？ http://mdp.tylingsoft.com/

**Comment by zipzou** [comment]
win10 + chrome

那个网站也可重现，EDGE正常

**Comment by tylerlong** [comment]
Mac 上 Chrome 也有问题，Safari 没问题。 估计是最新版的Chrome兼容性有问题。之前没发现，说明就是最近的 Chrome 的版本导致的。

我再看看。

不过我也准备抽空重写了。 不打算继续用 ACE editor 了。

**Comment by rusterx** [comment]
我也出现了这个问题， http://mdp.tylingsoft.com ，chrome的中文输入出现非常诡异的问题，不过这个软件非常棒。火狐似乎没有这个问题。我对windows7 + chrome

**Comment by rusterx** [comment]
用旧版的chrome浏览器没有中文输入这个问题。

**Comment by tylerlong** [comment]
问题已经解决。

我在 macOS 10.12.4， Chrome 56.0.2924.87 (64-bit) 已经无法重现问题了。

若还有问题，请留言或者创建新的 issue
