### ISSUE TITLE
Lated commit bugs

### ISSUE THREAD

**Issue by ajhalls** [tylingsoft/markdown-plus#86]
The latest commit looks for a bundle.js and css that don't exist in the repository.

We are including this project as part of a larger page and are getting some incompatibility errors with Select2.js and slimscroll with the version we downloaded last week.

When it is included on the page, the editor, toolbar and preview disappear after a moment unless the container is given an absolute size in pixels. It didn't seem to establish any size for itself, which then triggered the overflow hidden, but if I disable that property it has overlapping content positioned atop it. Putting it in an outer div and specifying the size helped, but we can't do a responsive layout with it.

Great project, we are looking forward to using it and chose it because of your activity in updating the project, and the activity you show in responding to issues. Thanks you very much and look forward to your thoughts.

**Comment by tylerlong** [comment]
Please run the following to build the project first:

```
yarn install
yarn build
```

I don't recommend you upgrading at the moment. You can just stick to the old version. Because I am doing massive refactoring which might break things. Please give me a month or so to deliver a stable version.

**Comment by ajhalls** [comment]
Should we run the commit from November then? I am really excited about the update, but wondering if it will create breaking changes that we would be better off waiting to implement till then? I do have a choice to wait if I need to, but if we can do it now and drop in the new code later, that would be great.

**Comment by tylerlong** [comment]
November's code should be very stable.  No new features was added since then. The recent change was about adopting webpack. So you can wait until I release 3.0.0 later this year.
