### ISSUE TITLE
Chinese IME issue

### ISSUE THREAD

**Issue by Bryant-Yang** [tylingsoft/markdown-plus#87]
Mac os Sierra 10.12.4

无论使用系统自带简体拼音，还是搜狗输入法，输入中文时，总是先输入了拼音字母，然后才在下一次输入之前的汉字。之前没这个现象，可能是os的问题。如果在其他系统未见此现象，也可能是其他软件造成的冲突。

**Comment by tylerlong** [comment]
Confimed.

I am working on fixing it.

Thanks

**Comment by tylerlong** [comment]
Fixed, please try version 2.4.0.

已修复，请尝试 2.4.0 版本。
