### ISSUE TITLE
Add Cmd+ / Cmd- font size increase/decrease

### ISSUE THREAD

**Issue by ssteinerx** [tylingsoft/markdown-plus#88]
I could swear this worked in a previous version, maybe not.

It sure would be handy.

**Comment by tylerlong** [comment]
Are you talking about the web version or the Mac app?

**Comment by ssteinerx** [comment]
I'm talking about the Mac version purchased from the App Store.

**Comment by tylerlong** [comment]
You can change the editor fonts via the preferences panel.

Do you also want to change the preview font size?

I agree keyboard shortcut is more handy. But it's not an official feature we've ever announced.

**Comment by ssteinerx** [comment]
On Apr 12, 2017, at 8:53 AM, Tyler Long wrote:

> You can change the editor fonts via the preferences panel.
> 
Yes, I know, and those are the ones I most often want to change.  The preview is usually less important at that point; I need the larger font to be able to focus on something in the editor.
> Do you also want to change the preview font size?
> 
Yes, but it's less critical.  If they had separate settings, that would be ideal.
> I agree keyboard shortcut is more handy. But it's not an official feature we've ever announced.
> 
Ok, I'll look forward to it for whenever/if ever you get around to it.
