### ISSUE TITLE
问一个问题，偶然性的不能输入，打上去的字会被自动替换

### ISSUE THREAD

**Issue by zhboner** [tylingsoft/markdown-plus#9]
也可能是操作不当

**Comment by zhboner** [comment]
一般出现在在前面的内容里插入的时候

**Comment by tylerlong** [comment]
网页版是吗？ 你看看控制台，是否有一些js文件没有加载上。我遇到过类似的问题，就是网络不是太好，某些js文件未能加载成功。

如果你能找出稳定重现问题的方式，我愿意深入研究下。

**Comment by zhboner** [comment]
不是网页版，是客户端。一般是在一段文章里插入的时候，会出现只能打1个字，后面打上去的替换掉前面的

**Comment by tylerlong** [comment]
印象中我也遇到过一次。测试那么久就那一次。 后来再没出现过。 如果你能找到稳定重现的方式，我就能诊断出原因了。 

我今天就要提交新版本去苹果商店审核了。大概不到一周审核通过就可以升级。 新版本不一定还有这个问题。 你要是发现规律就再留言，否则就等待下新版本吧。 感谢支持！
