### ISSUE TITLE
Paginated PDF import contains only empty pages

### ISSUE THREAD

**Issue by apahne** [tylingsoft/markdown-plus#90]
**Version**: Mac OS X standalone 2.5.0 (33)

Reproduce the issue:

1. Create New Document
2. Paste example Markdown from https://mdp.tylingsoft.com/
3. Create paginated PDF

Result: 
PDF document (attached) with 13 pages. The pages however are blank using the Mac OS X default PDF viewer.
Here the exported PDF:
[test2.pdf](https://github.com/tylingsoft/markdown-plus/files/1082968/test2.pdf)

Here a screenshot how it looks like in the Mac OS X default PDF viewer:
![image](https://user-images.githubusercontent.com/553153/27259404-e4d90cb8-5412-11e7-81aa-fb73058aebb2.png)

**Comment by tylerlong** [comment]
Open it with a different PDF viewer and you will see it's not empty.

For example, you can view it in Chrome.

I think it might be a bug of the default Mac PDF viewer but I am not sure.

**Comment by apahne** [comment]
Correct, the document renders OK in Chrome.

I validated it using https://www.pdf-online.com/osa/validate.aspx

The report says that "**The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted**."



>File	test2.pdf
Compliance	pdf1.4
Result	Document does not conform to PDF/A.
Details	
Validating file "test2.pdf" for conformance level pdf1.4
The object's identity 4 doesn't match with the object's reference identity 401.
The object's identity 4 doesn't match with the object's reference identity 389.
The object's identity 4 doesn't match with the object's reference identity 388.
The object's identity 4 doesn't match with the object's reference identity 387.
The object's identity 4 doesn't match with the object's reference identity 400.
The object's identity 4 doesn't match with the object's reference identity 386.
The object's identity 4 doesn't match with the object's reference identity 385.
The object's identity 4 doesn't match with the object's reference identity 384.
The object's identity 4 doesn't match with the object's reference identity 389.
The object's identity 4 doesn't match with the object's reference identity 388.
The object's identity 4 doesn't match with the object's reference identity 387.
The object's identity 4 doesn't match with the object's reference identity 381.
The object's identity 4 doesn't match with the object's reference identity 380.
The object's identity 4 doesn't match with the object's reference identity 379.
The object's identity 4 doesn't match with the object's reference identity 378.
The object's identity 4 doesn't match with the object's reference identity 377.
The object's identity 4 doesn't match with the object's reference identity 376.
The object's identity 4 doesn't match with the object's reference identity 375.
The object's identity 4 doesn't match with the object's reference identity 374.
The object's identity 4 doesn't match with the object's reference identity 365.
The object's identity 4 doesn't match with the object's reference identity 364.
The object's identity 4 doesn't match with the object's reference identity 363.
The object's identity 4 doesn't match with the object's reference identity 362.
The object's identity 4 doesn't match with the object's reference identity 350.
The object's identity 4 doesn't match with the object's reference identity 349.
The object's identity 4 doesn't match with the object's reference identity 348.
The object's identity 4 doesn't match with the object's reference identity 341.
The object's identity 4 doesn't match with the object's reference identity 340.
The object's identity 4 doesn't match with the object's reference identity 339.
The object's identity 4 doesn't match with the object's reference identity 338.
The object's identity 4 doesn't match with the object's reference identity 333.
The object's identity 4 doesn't match with the object's reference identity 332.
The object's identity 4 doesn't match with the object's reference identity 331.
The object's identity 4 doesn't match with the object's reference identity 330.
The object's identity 4 doesn't match with the object's reference identity 323.
The object's identity 4 doesn't match with the object's reference identity 320.
The object's identity 4 doesn't match with the object's reference identity 317.
The object's identity 4 doesn't match with the object's reference identity 314.
The object's identity 4 doesn't match with the object's reference identity 311.
The object's identity 4 doesn't match with the object's reference identity 381.
The object's identity 4 doesn't match with the object's reference identity 380.
The object's identity 4 doesn't match with the object's reference identity 379.
The object's identity 4 doesn't match with the object's reference identity 378.
The object's identity 4 doesn't match with the object's reference identity 377.
The object's identity 4 doesn't match with the object's reference identity 376.
The object's identity 4 doesn't match with the object's reference identity 375.
The object's identity 4 doesn't match with the object's reference identity 374.
The object's identity 4 doesn't match with the object's reference identity 365.
The object's identity 4 doesn't match with the object's reference identity 364.
The object's identity 4 doesn't match with the object's reference identity 363.
The object's identity 4 doesn't match with the object's reference identity 362.
The object's identity 4 doesn't match with the object's reference identity 357.
The object's identity 4 doesn't match with the object's reference identity 356.
The object's identity 4 doesn't match with the object's reference identity 355.
The object's identity 4 doesn't match with the object's reference identity 350.
The object's identity 4 doesn't match with the object's reference identity 349.
The object's identity 4 doesn't match with the object's reference identity 348.
The object's identity 4 doesn't match with the object's reference identity 341.
The object's identity 4 doesn't match with the object's reference identity 340.
The object's identity 4 doesn't match with the object's reference identity 339.
The object's identity 4 doesn't match with the object's reference identity 338.
The object's identity 4 doesn't match with the object's reference identity 333.
The object's identity 4 doesn't match with the object's reference identity 332.
The object's identity 4 doesn't match with the object's reference identity 331.
The object's identity 4 doesn't match with the object's reference identity 330.
The object's identity 4 doesn't match with the object's reference identity 323.
The object's identity 4 doesn't match with the object's reference identity 320.
The object's identity 4 doesn't match with the object's reference identity 317.
The object's identity 4 doesn't match with the object's reference identity 314.
The object's identity 4 doesn't match with the object's reference identity 311.
The object's identity 4 doesn't match with the object's reference identity 306.
The object's identity 4 doesn't match with the object's reference identity 305.
The object's identity 4 doesn't match with the object's reference identity 304.
The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted.
Done.

**Comment by tylerlong** [comment]
I will investigate.

For now please use this workaround: http://www.guidingtech.com/7566/chrome-print-to-pdf-convert-webpage-to-pdf/

Copy your markdown to https://mdp.tylingsoft.com/ and let Chrome print it to PDF.
